apiVersion: compute.yohancloud.com/v1
kind: Ec2Instance
metadata:
  name: ec2instance-sample-aws
  labels:
    app: simple-operators
    environment: aws
spec:
  instanceType: t3.micro
  amiId: ami-0236922087fa98b6e
  region: us-east-1
  availabilityZone: us-east-1a
  keyPair: operator-vm-key
  securityGroups:
    - sg-00f10006dc7fa4d95
  subnet: subnet-0617b63f842a1160b
  userData: |
    #!/bin/bash
    echo "Hello from Ec2Instance"
  tags:
    app: simple-operators
    environment: aws
  storage:
    rootVolume:
      size: 30
      type: gp3
      deviceName: /dev/xvda
      encrypted: true
    additionalVolumes:
      - size: 50
        type: gp3
        deviceName: /dev/xvdf
        encrypted: true
  associatePublicIP: true
